### PR TITLE
Implement right-click menu as widget instead of window

### PR DESCRIPTION
**Pull request by reidevries**
Hi! here is my reimplementation of RightClickMenu as a widget instead of a window.

Some notes:

- I named it MenuWidget instead of RightClickMenu, since it can be used as a generic drop-down menu
- I added a clang-format file. I only used it to format MenuWidget to fit the style of the rest of the code, but thought I'd include it since it might be useful to have project-wide formatting.
- My variable names use snake_case instead of camelCase, can change that if necessary
- I had to use chivo bold as the font. It seems the default font was disabled in upstream DPF because it wouldn't display any text unless I specified a font. That meant I had to change from a ✓ to a regular dash because the font didn't seem to include that glyph. I think it still looks ok tho
- We have to call a method on the top-level UI class to close the widget if the mouse goes out of bounds. With this configuration, instead of testing whether the mouse is outside of some bounds, we could just make it close whenever something else is clicked (like a control). I've left it testing if the mouse goes out of bounds but I don't think it would be hard to change the behaviour.
- If window-manager based window resizing is implemented, then it might break the mouse bounds checking in the case where a menu is shown while the window is being resized. I think there is probably a callback/event we can use to fix that tho.

### CODE REVIEW

**Comment by pdesaulniers** [comment]
Thanks! I'm looking at this :)

**Comment by reidevries** [comment]
> Hi! here is my reimplementation of RightClickMenu as a widget instead of a window.
> 
> Some notes:
> 
> * I named it MenuWidget instead of RightClickMenu, since it can be used as a generic drop-down menu
> * I added a clang-format file. I only used it to format MenuWidget to fit the style of the rest of the code, but thought I'd include it since it might be useful to have project-wide formatting.
> * My variable names use snake_case instead of camelCase, can change that if necessary
> * I had to use chivo bold as the font. It seems the default font was disabled in upstream DPF because it wouldn't display any text unless I specified a font. That meant I had to change from a ✓ to a regular dash because the font didn't seem to include that glyph. I think it still looks ok tho
> * We have to call a method on the top-level UI class to close the widget if the mouse goes out of bounds. With this configuration, instead of testing whether the mouse is outside of some bounds, we could just make it close whenever something else is clicked (like a control). I've left it testing if the mouse goes out of bounds but I don't think it would be hard to change the behaviour.
> * If window-manager based window resizing is implemented, then it might break the mouse bounds checking in the case where a menu is shown while the window is being resized. I think there is probably a callback/event we can use to fix that tho.

I

**Comment by reidevries** [comment]
oops accidentally closed it, sorry haha

I just tested by commenting out the contents of WolfShaperUI::onMotion, and yeah it actually seems to work fine like this. You can have the menu open, and click and drag a knob as usual :) I don't really know how to amend the pull request but it's a one line change

**Comment by pdesaulniers** [comment]
The widget works great!

Nitpick: can you please delete the leftover RightClickMenu.hpp.old and RightClickMenu.cpp files? These shouldn't be needed anymore :)

> I had to use chivo bold as the font. It seems the default font was disabled in upstream DPF because it wouldn't display any text unless I specified a font. That meant I had to change from a ✓ to a regular dash because the font didn't seem to include that glyph.

I think it looks fine, but I would prefer if we used the default "Deja Vu" font.

To load the font, you just need to call `loadSharedResources();` in the MenuWidget's constructor. Then, you can replace  `fontFace("chivo_bold");` with `fontFace(NANOVG_DEJAVU_SANS_TTF);`. Or, you can remove the `fontFace` call, and nanovg should pick the default font automatically.

> I don't really know how to amend the pull request but it's a one line change

You can simply push the changes to your fork on the master branch. The changes will be reflected in the pull request automatically.

**Comment by reidevries** [comment]
Cool, all those changes seemed to work fine!

**Comment by pdesaulniers** [comment]
All good! I'll merge this later today. Thanks!

**Pull request merged**
